inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - config/environments/development.rb
    - config/environments/production.rb
    - config/initializers/sorcery.rb
    - config/routes.rb
    - "db/schema.rb"
