inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  Exclude:
    - db/schema.rb

Metrics/BlockLength:
  Enabled: false

RSpec/MessageExpectation:
  Enabled: false

RSpec/MultipleDescribes:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/RepeatedExample:
  Enabled: false

RSpec/ScatteredSetup:
  Enabled: false
  