inherit_from: .rubocop_todo.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  NewCops: enable
  Exclude:
    - config/environments/development.rb
    - config/environments/production.rb
    - config/initializers/sorcery.rb
    - config/routes.rb
    - db/schema.rb

Metrics/BlockLength:
  Enabled: false
