databases:
  - name: myapp-database
    databaseName: myapp_production_m3gx
    user: igera0620
    region: singapore

services:
  - type: web
    name: myapp-database
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: myapp-database
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
