sorcery: 
  google_callback_url: 'https://new-project-1-vkar.onrender.com/oauth/callback?provider=google'
  line_callback_url: 'https://new-project-1-vkar.onrender.com/oauth/callback?provider=line'

default_url_options:
  protcol: 'https'
  host: 'example.com'