name: CI

on: [push, pull_request]

jobs:
  rubocop_rspec:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15  # PostgreSQLのバージョンを指定
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_database
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: GitHubリポジトリのコードを取得
        uses: actions/checkout@v3

      - name: Rubyをセットアップ
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true

      - name: PostgreSQLの設定
        run: |
          sudo apt-get -yqq install libpq-dev
          cp config/database.github.yml config/database.yml

      - name: データベースを作成
        env:
          RAILS_ENV: test
        run: |
          bundle exec rails db:create
          bundle exec rails db:migrate

      - name: RuboCopを実行
        run: bundle exec rubocop

      - name: RSpecを実行
        run: bundle exec rspec
