name: CI

on: [push, pull_request]

jobs:
  rubocop_rspec:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_database
          GITHUB_ACTIONS: true
          CI: true
        ports:
          - 5432:5432
        options: |
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --network-alias=db

    steps:
      - name: GitHubリポジトリのコードを取得
        uses: actions/checkout@v3

      - name: Rubyをセットアップ
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true

      - name: 環境変数の設定（OPENAI_ACCESS_TOKEN）
        run: echo "OPENAI_ACCESS_TOKEN=${{ secrets.OPENAI_ACCESS_TOKEN }}" >> $GITHUB_ENV

      - name: PostgreSQLの設定
        run: |
          sudo apt-get -yqq install libpq-dev
          cp config/database.github.yml config/database.yml

      - name: PostgreSQLが起動するまで待機
        run: |
          for i in {1..10}; do
            pg_isready -h localhost -p 5432 && echo "PostgreSQL is ready!" && exit 0
            echo "Waiting for PostgreSQL..."
            sleep 3
          done
          echo "PostgreSQL did not start in time" && exit 1

      - name: データベースを作成
        env:
          RAILS_ENV: test
          DATABASE_URL: "postgres://postgres:password@localhost:5432/test_database"
        run: |
          bundle exec rails db:create
          bundle exec rails db:migrate

      - name: RuboCopを実行
        run: bundle exec rubocop

      - name: RSpecを実行
        run: bundle exec rspec
