name: CI

on: [push, pull_request]

jobs:
  rubocop_rspec:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_database
          GITHUB_ACTIONS: "true"
          CI: "true"
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres -h 127.0.0.1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: GitHubリポジトリのコードを取得
        uses: actions/checkout@v3

      - name: Rubyをセットアップ
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true

      - name: 環境変数の設定（OPENAI_ACCESS_TOKEN）
        run: echo "OPENAI_ACCESS_TOKEN=${{ secrets.OPENAI_ACCESS_TOKEN }}" >> $GITHUB_ENV

      - name: PostgreSQLの設定
        run: |
          sudo apt-get -yqq install libpq-dev
          cp config/database.github.yml config/database.yml

      - name: データベースを作成
        env:
          RAILS_ENV: test
          DATABASE_URL: "postgres://postgres:password@127.0.0.1:5432/new_project_test"
        run: |
          bundle exec rails db:create
          bundle exec rails db:migrate

      - name: RuboCopを実行
        run: bundle exec rubocop

      - name: RSpecを実行
        run: bundle exec rspec
